docs: add vcs url as part of usage information
konveyor/move2kube pull request #1032
Opened 2023-05-08 15:41 UTC by venkatbandarupalli

I have followed

```
pip install --help
```
<img width="1539" alt="Screen Shot 2023-05-08 at 10 39 29 AM" src="https://user-images.githubusercontent.com/125749977/236867635-282b0c1c-b396-450b-900d-643dc896ec23.png">

2023-05-08 17:19 UTC, kmehant requested changes

2023-05-08 17:19 UTC, kmehant commented on cmd/plan.go
> +	planCmd.Flags().StringVarP(&flags.srcpath, sourceFlag, "s", "", "Specify source directory or a VCS url.")
Can you change VCS to `git`? Can you make this change in all the places?

Once you are ready with the git-support page, you can reference the link here in a `(` and `)`

2023-05-12 10:09 UTC, kmehant approved these changes

2023-05-12 10:24 UTC, HarikrishnanBalagopal approved these changes

2023-05-12 10:24 UTC, merged