fix: take destNamespace from user
konveyor/move2kube pull request #1069
Opened 2023-08-01 20:39 UTC by SVKREP

I am new to open source. I made the PR referring to this link: https://github.com/konveyor/move2kube/blob/main/contributing.md Please LMK if I need to correct something. 

This PR Solves: https://github.com/konveyor/move2kube/issues/930

I've built and tried Move2kube project. I am having trouble in testing this change. Can somebody suggest. Thanks!

2023-08-02 13:48 UTC, HarikrishnanBalagopal requested changes

2023-08-02 13:48 UTC, HarikrishnanBalagopal commented on transformer/kubernetes/apiresource/argocdapplication.go
> +		logrus.Errorf("failed to ask a question to the user in order to parameterize a k8s resource: %+v\nError: %q", prob, err)
we need to return on error.

Don't use the `FetchAnswer` function use the `FetchStringAnswer` function https://github.com/konveyor/move2kube/blob/817b8c901e9d3622a7fcbf6db55a34a08427ca90/qaengine/engine.go#L210

Example: https://github.com/konveyor/move2kube/blob/817b8c901e9d3622a7fcbf6db55a34a08427ca90/transformer/kubernetes/apiresource/triggertemplate.go#L91C8-L97

2023-08-02 13:48 UTC, HarikrishnanBalagopal commented on transformer/kubernetes/apiresource/argocdapplication.go
> +		logrus.Errorf("failed to ask a question to the user in order to parameterize a k8s resource: %+v\nError: the answer was not a string", prob)
we need to return on error

2023-08-15 04:39 UTC, seshapad commented
@SVKREP Please rebase your branch to have the latest upstream.

2023-08-23 14:31 UTC, Akash-Nayak requested changes
Hi @SVKREP, can you please make the changes requested by @HarikrishnanBalagopal on this PR-
https://github.com/konveyor/move2kube/pull/1069/files#r1281931155
https://github.com/konveyor/move2kube/pull/1069/files#r1281931265

2023-09-04 07:05 UTC, SVKREP commented
Hi Team, @Akash-Nayak, @HarikrishnanBalagopal, @kmehant. Can someone please review this in your free time!

2023-09-04 09:18 UTC, Akash-Nayak commented on transformer/kubernetes/apiresource/argocdapplication.go
> +		"Enter destination namespace for argo cd pipeline",
Can you please update the string to "Enter the destination namespace for the Argo CD pipeline"

2023-09-04 09:18 UTC, Akash-Nayak commented on transformer/kubernetes/apiresource/argocdapplication.go
> +		[]string{"If this is not relevant to you then give an empty string to remove it from the YAML."},
Can we also update the context to `[]string{If Argo CD pipeline is not relevant to you, then leave empty to use the default value for it.}`

2023-09-04 10:25 UTC, SVKREP commented
@Akash-Nayak, I have made the changes, Thanks!

2023-09-05 12:38 UTC, HarikrishnanBalagopal approved these changes
LGTM

2023-09-05 12:39 UTC, merged