Adding ingress fan-out and host sub-domain generation
konveyor/move2kube pull request #107
Opened 2020-10-23 06:12 UTC by seshapad

Signed-off-by: seshapad <seshapad@in.ibm.com>

2020-10-23 07:15 UTC, ashokponkumar requested changes

2020-10-23 07:57 UTC, seshapad commented on internal/types/ir.go
> +	IngressPath string //Ingress fan-out path
@ashokponkumar 
Are you suggesting that we provide serviceRelPath for each service in the path file? That would be nice actually...will allow users to customize.

2020-10-23 07:57 UTC, seshapad commented on internal/types/ir.go
> +	IngressHost    string
Yes. This should be queried from the cluster.

2020-10-23 07:58 UTC, seshapad commented on internal/types/ir.go
> +func (service *Service) IsServiceExposed() bool {
Could you elaborate?

2020-10-23 07:59 UTC, seshapad commented on internal/parameterizer/ingressparameterizer.go
> +	isHelm := (ir.Kubernetes.ArtifactType != plantypes.Yamls)
ok.

2020-10-23 09:32 UTC, seshapad commented on internal/types/ir.go
> +func (service *Service) IsServiceExposed() bool {
empty path means we are not exposing the service.

2020-10-23 10:02 UTC, HarikrishnanBalagopal commented on internal/types/ir.go
> +	IngressPath string //Ingress fan-out path
@ashokponkumar @seshapad so can we talk about that? it's related to https://github.com/konveyor/move2kube/issues/61

2020-10-24 03:33 UTC, ashokponkumar approved these changes

2020-10-24 03:33 UTC, merged