test: add tests for replicateDeletionCallback
konveyor/move2kube pull request #1077
Opened 2023-08-18 13:22 UTC by Prakhar-Agarwal-byte

Added test for replicateDeletionCallback in the filesystem package. These tests cover 2 cases

1. Destination folder gets created
2. Created destination folder has the same permissions as the source.

Fixes a part of https://github.com/konveyor/move2kube/issues/881

2023-08-21 04:50 UTC, seshapad commented
@Prakhar-Agarwal-byte Seems like some automated test has failed. Can you please check and fix your code to address it.

2023-08-21 05:15 UTC, HarikrishnanBalagopal requested changes

2023-08-21 05:15 UTC, HarikrishnanBalagopal commented on filesystem/replicator_test.go
> +			sourceDir := "testdata/src"
The source doesn't exist. It needs to exist so that the destination folder can be created with the same permissions.

2023-08-21 05:15 UTC, HarikrishnanBalagopal commented on filesystem/replicator_test.go
> +		t.Run("test for destination folder gets created", func(t *testing.T) {
We can remove this 1st test and just keep the 2nd test that tests for both creation and permission.

2023-08-26 15:25 UTC, HarikrishnanBalagopal approved these changes
LGTM

2023-08-27 02:44 UTC, merged