test: added test for mergeDeletionCallBack
konveyor/move2kube pull request #1125
Opened 2023-12-17 16:10 UTC by satyazzz123

## test for mergeDeletionCallBack
ii) test for scenario which checks for permissions of the destination directory to match the permissions of the source file when both the source file and destination directory exist

fixes a part of #881

2023-12-18 12:37 UTC, satyazzz123 commented
@kmehant @seshapad please review this PR.

2024-01-04 08:42 UTC, HarikrishnanBalagopal requested changes

2024-01-04 08:42 UTC, HarikrishnanBalagopal commented on filesystem/merger_test.go
> +	if destInfo.Mode().Perm() != sourceFileInfo.Mode().Perm() {
Also check if destination is indeed a directory

2024-01-04 08:42 UTC, HarikrishnanBalagopal commented on filesystem/merger_test.go
> +	// Call the merge function
```suggestion
	// Call the merge deletion callback function
```

2024-01-04 16:02 UTC, satyazzz123 commented
@HarikrishnanBalagopal I have addressed the requested changes . Please have a look . Thank you

2024-01-05 09:36 UTC, HarikrishnanBalagopal approved these changes
LGTM

2024-01-05 09:36 UTC, merged