feat: add support for file path
konveyor/move2kube pull request #1141
Opened 2024-01-31 11:51 UTC by mohit-marathe

Fixes: #1039

2024-01-31 13:34 UTC, mohit-marathe commented
@kmehant @HarikrishnanBalagopal  Please review this PR!

2024-03-21 09:58 UTC, HarikrishnanBalagopal requested changes
@kmehant have we tested this with both Docker and Podman?

2024-03-21 09:58 UTC, HarikrishnanBalagopal commented on environment/container/dockerengine.go
> +        fi, err := os.Stat(sp)
Fix indentation. Use `go fmt`.
If you are using a text editor like VSCode, VIM, Sublime, etc. installing the Golang extension automatically runs the go formatter when you save the file.

2024-03-21 09:58 UTC, HarikrishnanBalagopal commented on environment/container/dockerengine.go
> +            err = copyDirToContainer(e.ctx, e.cli, containerID, sp, newDestPath)
If `copyDirToContainer` is being used to copy files then we should rename it as well.

2025-02-27 09:02 UTC, closed without merging