feat: Support WASM external transformers using Wazero runtime
konveyor/move2kube pull request #1172
Opened 2024-04-04 14:50 UTC by shashank381

2024-04-10 07:03 UTC, kmehant commented
@shashank381 Thank you, one of us would review it.

2024-04-10 10:00 UTC, HarikrishnanBalagopal requested changes

2024-04-10 10:00 UTC, HarikrishnanBalagopal commented on transformer/external/wasmtransformer.go
> +		keyValue := strings.SplitN(envVar, wasmEnvDelimiter, 2)
Why are we joining the key and value with = delimiter and then splitting again?

2024-04-10 10:01 UTC, HarikrishnanBalagopal commented on transformer/external/wasmtransformer.go
> +		keyValue := strings.SplitN(envVar, wasmEnvDelimiter, 2)
Also fix the DCO check by signing

2024-04-12 05:12 UTC, kmehant commented
```
INFO[0001] Planning started on its sub directories      
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/django/pom.xml: file does not exist

wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/django/simplewebapp/pom.xml: file does not exist

wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/django/webroot/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/django/webroot/migrations/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/golang/pom.xml: file does not exist

wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/java-gradle/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/java-gradle/gradle/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/java-gradle/gradle/wrapper/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/java-gradle/src/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/java-gradle/src/main/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/java-gradle/src/main/java/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/java-gradle/src/main/java/com/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/java-gradle/src/main/java/com/myuser/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/java-gradle/src/main/webapp/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/java-gradle/src/main/webapp/WEB-INF/pom.xml: file does not exist
INFO[0004] Identified 1 named services and 0 to-be-named services in java-maven 
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/java-war/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/nodejs/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/php/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/python/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/ruby/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/ruby/views/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/rust/pom.xml: file does not exist
wasm stat failed: stat /Users/haribala/temp/temp-m2k-cli-wasm/t1/language-platforms/rust/src/pom.xml: file does not exist
INFO[0005] Planning finished on its sub directories    
```

Can we check stat is being checked in every possible location in the source artifact folders? @shashank381

2024-04-19 05:09 UTC, HarikrishnanBalagopal approved these changes
LGTM

2024-04-19 05:10 UTC, merged