Netflix OSS transformation (zuul + service module + eureka)
konveyor/move2kube pull request #533
Opened 2021-07-01 05:14 UTC by kmehant

Signed-off-by: K mehant <411843@student.nitandhra.ac.in>

2021-07-02 18:45 UTC, ashokponkumar requested changes

2021-07-02 18:45 UTC, ashokponkumar commented on assets/filepermissions.yaml
> +"inbuilt/transformers/.DS_Store" : 0644
Can we remove this?

2021-07-02 18:45 UTC, ashokponkumar commented on assets/filepermissions.yaml
> +"inbuilt/transformers/executable/.DS_Store" : 0644
Remove this

2021-07-02 18:45 UTC, ashokponkumar commented on assets/filepermissions.yaml
> +"inbuilt/transformers/executable/s2i/.DS_Store" : 0644
Remove this

2021-07-02 18:45 UTC, ashokponkumar commented on go.mod
> +	github.com/vifraa/gopom v0.1.0 // indirect
I assume we are not using this rather your own version. So we can remove this reference.

2021-07-02 18:45 UTC, ashokponkumar commented on internal/transformer/classes/analysers/zuulanalyser.go
> +	//  "encoding/xml"
Remove all the commented lines

2021-07-02 18:45 UTC, ashokponkumar commented on internal/transformer/classes/analysers/zuulanalyser.go
> +
Remove the empty lines

2021-07-02 23:09 UTC, kmehant commented
@ashokponkumar Thank you for the review! I have addressed the changes!

2021-07-03 04:03 UTC, ashokponkumar approved these changes

2021-07-03 04:04 UTC, merged