feat: Include cloud-foundry vcap variables in storage
konveyor/move2kube pull request #671
Opened 2021-12-06 16:10 UTC by seshapad

2021-12-06 18:34 UTC, ashokponkumar requested changes
Really nice work @seshapad ! 

Few suggestions...

Also, In default move2kube flow, we should surface these environment variables in deployment and deploymentconfig too. Isn't it?

2021-12-06 18:34 UTC, ashokponkumar commented on transformer/cloudfoundrytransformer.go
> +						ir.Storages = append(ir.Storages, irtypes.Storage{Name: config.ServiceName, Content: vcapVariables})
Do we not want to set the type of storage to secret? We should possibly expose it as a flag and do it only in certain cases.

2021-12-06 18:34 UTC, ashokponkumar commented on transformer/cloudfoundrytransformer.go
> +				}
Shouldn't the ones that are already environment variables take precedence over VCAP, since they were manually set?

2021-12-06 18:34 UTC, ashokponkumar commented on transformer/cloudfoundrytransformer.go
> +	logrus.Infof("Number of services in m2k-collect dump [vcap] %d", len(services))
This should be a debug message

2022-01-06 16:02 UTC, ashokponkumar requested changes
Nice work Nabha. Few points...

2022-01-07 04:56 UTC, seshapad commented on transformer/cloudfoundrytransformer.go
> +	json.Unmarshal([]byte(vcapService), &serviceInstanceMap)
done

2022-01-07 04:57 UTC, seshapad commented on transformer/cloudfoundrytransformer.go
> +			envName := prefix + "_" + name
done

2022-01-07 04:58 UTC, seshapad commented on transformer/cloudfoundrytransformer.go
> +			envName := fmt.Sprintf("%s_%v", prefix, name)
yes. changed variable name to index.

2022-01-07 11:06 UTC, ashokponkumar requested changes

2022-01-07 11:06 UTC, ashokponkumar commented on transformer/cloudfoundrytransformer.go
> +	}
isn't this giving the highest priority to the manifest file?

2022-01-07 11:45 UTC, ashokponkumar approved these changes

2022-01-07 11:48 UTC, merged